import {
    Article,
    ArticlesTag,
    CartProduct,
    Course,
    MenuItem,
    TFilteringCourse,
    UserComment,
    UserCounterItem,
    UserNotification,
    UserPanelMenuLink,
} from "./definition";

export const menuItems: MenuItem[] = [
    {
        id: 1,
        title: "دسته بندی آموزش ها",
        href: "/courses",
        links: [
            {
                id: 1,
                title: "فرانت اند",
                href: "#",
                subLinks: [
                    {
                        id: 1,
                        title: "جاوا اسکریپت",
                        href: "#",
                    },
                    {
                        id: 2,
                        title: "نکست جی اس",
                        href: "#",
                    },
                    {
                        id: 3,
                        title: "انگیولار",
                        href: "#",
                    },
                    {
                        id: 4,
                        title: "تایپ اسکریپت",
                        href: "#",
                    },
                    {
                        id: 5,
                        title: "ری اکت",
                        href: "#",
                    },
                    {
                        id: 6,
                        title: "ویو جی اس",
                        href: "#",
                    },
                    {
                        id: 7,
                        title: "نود جی اس",
                        href: "#",
                    },
                    {
                        id: 8,
                        title: "جنگو",
                        href: "#",
                    },
                    {
                        id: 9,
                        title: "اکسپرس جی اس",
                        href: "#",
                    },
                    {
                        id: 10,
                        title: "پی اچ پی",
                        href: "#",
                    },
                    {
                        id: 11,
                        title: "لاراول",
                        href: "#",
                    },
                    {
                        id: 12,
                        title: "سی شارپ",
                        href: "#",
                    },
                ],
            },
            {
                id: 2,
                title: "بک اند",
                href: "#",
                subLinks: [
                    {
                        id: 1,
                        title: "جاوا اسکریپت",
                        href: "#",
                    },
                    {
                        id: 2,
                        title: "نکست جی اس",
                        href: "#",
                    },
                    {
                        id: 3,
                        title: "انگیولار",
                        href: "#",
                    },
                    {
                        id: 4,
                        title: "تایپ اسکریپت",
                        href: "#",
                    },
                    {
                        id: 5,
                        title: "ری اکت",
                        href: "#",
                    },
                    {
                        id: 6,
                        title: "ویو جی اس",
                        href: "#",
                    },
                    {
                        id: 7,
                        title: "نود جی اس",
                        href: "#",
                    },
                    {
                        id: 8,
                        title: "جنگو",
                        href: "#",
                    },
                    {
                        id: 9,
                        title: "اکسپرس جی اس",
                        href: "#",
                    },
                    {
                        id: 10,
                        title: "پی اچ پی",
                        href: "#",
                    },
                    {
                        id: 11,
                        title: "لاراول",
                        href: "#",
                    },
                    {
                        id: 12,
                        title: "سی شارپ",
                        href: "#",
                    },
                ],
            },
            {
                id: 3,
                title: "دیتاساینس",
                href: "#",
            },
            {
                id: 4,
                title: "زبانهای برنامه نویسی",
                href: "#",
            },
            {
                id: 5,
                title: "توسعه بازی",
                href: "#",
            },
            {
                id: 6,
                title: "برنامه نویسی موبایل",
                href: "#",
            },
        ],
    },
    {
        id: 2,
        title: "مقالات آموزشی",
        href: "/articles",
    },
    {
        id: 3,
        title: "تمامی صفحات",
        href: "#",
        links: [
            {
                id: 1,
                title: "ثبت نام",
                href: "/register",
            },
            {
                id: 2,
                title: "ورود",
                href: "/login",
            },
            {
                id: 3,
                title: "دوره ها",
                href: "/courses",
            },
            {
                id: 4,
                title: "مقاله ها",
                href: "/articles",
            },
            {
                id: 5,
                title: "جزییات دوره",
                href: "/course-detail/react-js",
            },
            {
                id: 6,
                title: "جزییات مقاله",
                href: "/article-detail/backend-vs-frontend",
            },
            {
                id: 7,
                title: "پنل کاربری",
                href: "/dashboard/counter",
            },
            {
                id: 8,
                title: "سبد خرید",
                href: "/orders",
            },
        ],
    },
];

export const userProfileItems = [
    {
        id: 1,
        title: "مشاهده پروفایل",
        href: "/user-panel/counter",
    },
    {
        id: 2,
        title: "پنل کاربری",
        href: "/user-panel",
    },
    {
        id: 3,
        title: "خروج از حساب",
        href: "/login",
    },
    {
        id: 4,
        title: "پنل مدیریت",
        href: "/admin-panel",
    },
];

export const services = [
    {
        id: 1,
        title: "چالش برانگیز",
    },
    {
        id: 2,
        title: "پروژه محور",
    },
    {
        id: 3,
        title: "جامع",
    },
    {
        id: 4,
        title: "به روز",
    },
    {
        id: 5,
        title: "ویدیویی",
    },
    {
        id: 6,
        title: "منتورشیپ",
    },
];

export const courses: Course[] = [
    {
        id: 1,
        title: "آموزش فلاتر از صفر",
        price: 1_990_000,
        costPrice: 1_250_000,
        isFree: false,
        time: 25,
        sections: 12,
        isCompleted: false,
        teacher: "حسین رستمی",
        img: "/images/Courses/03.jpg",
        teacherImg: "/images/profile.jpeg",
        category: "اندروید",
        offer: 12,
        href: "#",
    },
    {
        id: 2,
        title: "آموزش پروژه محور ری اکت و نکست",
        price: 1_560_000,
        costPrice: 0,
        isFree: false,
        time: 32,
        sections: 24,
        isCompleted: true,
        teacher: "حسین رستمی",
        img: "/images/Courses/01.jpg",
        teacherImg: "/images/profile.jpeg",
        category: "فرانت اند",
        offer: 0,
        href: "#",
    },
    {
        id: 3,
        title: "قدم صفر برنامه نویسی",
        price: 0,
        costPrice: 0,
        isFree: true,
        time: 8,
        sections: 4,
        isCompleted: true,
        teacher: "حسین رستمی",
        img: "/images/Courses/02.jpg",
        teacherImg: "/images/profile.jpeg",
        category: "فرانت اند",
        offer: 0,
        href: "#",
    },
    {
        id: 4,
        title: "آموزش ساخت ربات تلگرام با لاراول",
        price: 890_000,
        costPrice: 760_000,
        isFree: false,
        time: 12,
        sections: 5,
        isCompleted: true,
        teacher: "حسین رستمی",
        img: "/images/Courses/laravel.jpg",
        teacherImg: "/images/profile.jpeg",
        category: "اندروید",
        offer: 12,
        href: "#",
    },
    {
        id: 5,
        title: "دوره آموزش Redux",
        price: 1_000_000,
        costPrice: 0,
        isFree: false,
        time: 16,
        sections: 18,
        isCompleted: false,
        teacher: "حسین رستمی",
        img: "/images/Courses/redux.jpg",
        teacherImg: "/images/profile.jpeg",
        category: "فرانت اند",
        offer: 0,
        href: "#",
    },
    {
        id: 6,
        title: "دوره آموزش TailwindCss",
        price: 0,
        costPrice: 0,
        isFree: true,
        time: 15,
        sections: 7,
        isCompleted: true,
        teacher: "حسین رستمی",
        img: "/images/Courses/tailwind.jpg",
        teacherImg: "/images/profile.jpeg",
        category: "فرانت اند",
        offer: 0,
        href: "#",
    },
    {
        id: 7,
        title: "آموزش کامل VsCode",
        price: 0,
        costPrice: 0,
        isFree: true,
        time: 2,
        sections: 1,
        isCompleted: true,
        teacher: "حسین رستمی",
        img: "/images/Courses/vscode.jpg",
        teacherImg: "/images/profile.jpeg",
        category: "فرانت اند",
        offer: 0,
        href: "#",
    },
    {
        id: 8,
        title: "آموزش جامع ووکامرس",
        price: 650_000,
        costPrice: 0,
        isFree: false,
        time: 12,
        sections: 4,
        isCompleted: true,
        teacher: "حسین رستمی",
        img: "/images/Courses/woocommerce.jpg",
        teacherImg: "/images/profile.jpeg",
        category: "فرانت اند",
        offer: 0,
        href: "#",
    },
    {
        id: 9,
        title: "دوره آموزش Redux",
        price: 1_000_000,
        costPrice: 0,
        isFree: false,
        time: 16,
        sections: 18,
        isCompleted: false,
        teacher: "حسین رستمی",
        img: "/images/Courses/redux.jpg",
        teacherImg: "/images/profile.jpeg",
        category: "فرانت اند",
        offer: 0,
        href: "#",
    },
    {
        id: 10,
        title: "دوره آموزش TailwindCss",
        price: 0,
        costPrice: 0,
        isFree: true,
        time: 15,
        sections: 7,
        isCompleted: true,
        teacher: "حسین رستمی",
        img: "/images/Courses/tailwind.jpg",
        teacherImg: "/images/profile.jpeg",
        category: "فرانت اند",
        offer: 0,
        href: "#",
    },
    {
        id: 11,
        title: "آموزش کامل VsCode",
        price: 0,
        costPrice: 0,
        isFree: true,
        time: 2,
        sections: 1,
        isCompleted: true,
        teacher: "حسین رستمی",
        img: "/images/Courses/vscode.jpg",
        teacherImg: "/images/profile.jpeg",
        category: "فرانت اند",
        offer: 0,
        href: "#",
    },
    {
        id: 12,
        title: "آموزش جامع ووکامرس",
        price: 650_000,
        costPrice: 0,
        isFree: false,
        time: 12,
        sections: 4,
        isCompleted: true,
        teacher: "حسین رستمی",
        img: "/images/Courses/woocommerce.jpg",
        teacherImg: "/images/profile.jpeg",
        category: "فرانت اند",
        offer: 0,
        href: "#",
    },
];

export const latestCourses: Course[] = [
    {
        id: 1,
        title: "آموزش فلاتر از صفر",
        price: 1_990_000,
        costPrice: 1_250_000,
        isFree: false,
        time: 25,
        sections: 12,
        isCompleted: false,
        teacher: "حسین رستمی",
        img: "/images/Courses/03.jpg",
        teacherImg: "/images/profile.jpeg",
        category: "اندروید",
        offer: 12,
        href: "#",
    },
    {
        id: 2,
        title: "آموزش پروژه محور ری اکت و نکست",
        price: 1_560_000,
        costPrice: 0,
        isFree: false,
        time: 32,
        sections: 24,
        isCompleted: true,
        teacher: "حسین رستمی",
        img: "/images/Courses/01.jpg",
        teacherImg: "/images/profile.jpeg",
        category: "فرانت اند",
        offer: 0,
        href: "#",
    },
    {
        id: 3,
        title: "قدم صفر برنامه نویسی",
        price: 0,
        costPrice: 0,
        isFree: true,
        time: 8,
        sections: 4,
        isCompleted: true,
        teacher: "حسین رستمی",
        img: "/images/Courses/02.jpg",
        teacherImg: "/images/profile.jpeg",
        category: "فرانت اند",
        offer: 0,
        href: "#",
    },
];

export const latestArticles: Article[] = [
    {
        id: 1,
        title: "تفاوت بک اند و فرانت اند",
        img: "/images/Articles/backend-vs-frontend.jpg",
        time: "20:00",
        writer: "حسین رستمی",
        writerImg: "/images/profile.jpeg",
        category: "فرانت اند",
        href: "#",
        writerHref: "#",
    },
    {
        id: 2,
        title: "Sass چیست ؟",
        img: "/images/Articles/sass.jpg",
        time: "15:00",
        writer: "حسین رستمی",
        writerImg: "/images/profile.jpeg",
        category: "فرانت اند",
        href: "#",
        writerHref: "#",
    },
    {
        id: 3,
        title: "کار با توابع در جاوااسکریپت",
        img: "/images/Articles/functions.jpg",
        time: "32:00",
        writer: "حسین رستمی",
        writerImg: "/images/profile.jpeg",
        category: "فرانت اند",
        href: "#",
        writerHref: "#",
    },
    {
        id: 4,
        title: "تفاوت جاوااسکریپت و اکمااسکریپت",
        img: "/images/Articles/js-vs-ecma.jpg",
        time: "10:00",
        writer: "حسین رستمی",
        writerImg: "/images/profile.jpeg",
        category: "بک اند",
        href: "#",
        writerHref: "#",
    },
];

export const useFullLinks = [
    {
        id: 1,
        title: "قوانین و مقررات",
        href: "#",
    },
    {
        id: 2,
        title: "مدرسان",
        href: "#",
    },
    {
        id: 3,
        title: "درباره نابغه",
        href: "#",
    },
    {
        id: 4,
        title: "ارتباط با ما",
        href: "#",
    },
];

export const socialMediaLinks = [
    {
        id: 1,
        title: "telegram",
        href: "#",
    },
    {
        id: 2,
        title: "instagram",
        href: "#",
    },
    {
        id: 3,
        title: "youtube",
        href: "#",
    },
];

export const courseTypes: TFilteringCourse[] = [
    { id: 1, title: "پولی" },
    { id: 2, title: "رایگان" },
    { id: 3, title: "همه" },
];

export const courseCategories: TFilteringCourse[] = [
    { id: 1, title: "فرانت اند" },
    { id: 2, title: "بک اند" },
    { id: 3, title: "اندروید" },
];

export const sortingTypes: TFilteringCourse[] = [
    { id: 1, title: "جدیدترین" },
    { id: 2, title: "پرفروش ترین" },
    { id: 3, title: "گران ترین" },
    { id: 4, title: "ارزان ترین" },
];

export const articlesFilteringTags: ArticlesTag[] = [
    {
        id: 1,
        title: "لاراول",
        href: "#",
    },
    {
        id: 2,
        title: "پی_اچ_پی",
        href: "#",
    },
    {
        id: 3,
        title: "تلویند",
        href: "#",
    },
    {
        id: 4,
        title: "جاوااسکریپت",
        href: "#",
    },
    {
        id: 5,
        title: "فلاتر",
        href: "#",
    },
    {
        id: 6,
        title: "وردپرس",
        href: "#",
    },
    {
        id: 7,
        title: "متفرقه",
        href: "#",
    },
];

export const articles: Article[] = [
    {
        id: 1,
        title: "تفاوت بک اند و فرانت اند",
        img: "/images/Articles/backend-vs-frontend.jpg",
        time: "20:00",
        writer: "حسین رستمی",
        writerImg: "/images/profile.jpeg",
        category: "فرانت اند",
        href: "#",
        writerHref: "#",
    },
    {
        id: 2,
        title: "Sass چیست ؟",
        img: "/images/Articles/sass.jpg",
        time: "15:00",
        writer: "حسین رستمی",
        writerImg: "/images/profile.jpeg",
        category: "فرانت اند",
        href: "#",
        writerHref: "#",
    },
    {
        id: 3,
        title: "کار با توابع در جاوااسکریپت",
        img: "/images/Articles/functions.jpg",
        time: "32:00",
        writer: "حسین رستمی",
        writerImg: "/images/profile.jpeg",
        category: "فرانت اند",
        href: "#",
        writerHref: "#",
    },
    {
        id: 4,
        title: "تفاوت جاوااسکریپت و اکمااسکریپت",
        img: "/images/Articles/js-vs-ecma.jpg",
        time: "10:00",
        writer: "حسین رستمی",
        writerImg: "/images/profile.jpeg",
        category: "بک اند",
        href: "#",
        writerHref: "#",
    },
    {
        id: 5,
        title: "آموزش کار با MarkDown",
        img: "/images/Articles/markdown.jpg",
        time: "20:00",
        writer: "حسین رستمی",
        writerImg: "/images/profile.jpeg",
        category: "فرانت اند",
        href: "#",
        writerHref: "#",
    },
    {
        id: 6,
        title: "بهترین تم های vscode",
        img: "/images/Articles/theme.jpg",
        time: "15:00",
        writer: "حسین رستمی",
        writerImg: "/images/profile.jpeg",
        category: "فرانت اند",
        href: "#",
        writerHref: "#",
    },
    {
        id: 7,
        title: "تایپ اسکریپت چیست ؟ (TypeScript)",
        img: "/images/Articles/typescript.jpg",
        time: "32:00",
        writer: "حسین رستمی",
        writerImg: "/images/profile.jpeg",
        category: "فرانت اند",
        href: "#",
        writerHref: "#",
    },
    {
        id: 8,
        title: "وردپرس چقدر امن است ؟",
        img: "/images/Articles/wordpress-secure.jpg",
        time: "10:00",
        writer: "حسین رستمی",
        writerImg: "/images/profile.jpeg",
        category: "بک اند",
        href: "#",
        writerHref: "#",
    },
];

export const articleCategories = [
    { id: "1", title: "فرانت اند" },
    { id: "2", title: "بک اند" },
    { id: "3", title: "امنیت" },
    { id: "4", title: "طراحی سایت" },
    { id: "5", title: "فلاتر" },
];

export const cartProducts: CartProduct[] = [
    {
        id: 1,
        title: "آموزش فلاتر از صفر",
        price: 1_990_000,
        costPrice: 1_250_000,
        isFree: false,
        time: 25,
        sections: 12,
        isCompleted: true,
        teacher: "حسین رستمی",
        img: "/images/Courses/03.jpg",
        teacherImg: "/images/profile.jpeg",
        offer: 12,
        href: "#",
    },
    {
        id: 2,
        title: "آموزش پروژه محور ری اکت و نکست",
        price: 1_560_000,
        costPrice: 0,
        isFree: false,
        time: 32,
        sections: 24,
        isCompleted: true,
        teacher: "حسین رستمی",
        img: "/images/Courses/01.jpg",
        teacherImg: "/images/profile.jpeg",
        offer: 12,
        href: "#",
    },
];

export const userPanelMenuLinks: UserPanelMenuLink[] = [
    {
        id: 1,
        title: "پیشخوان",
        href: "counter",
    },
    {
        id: 2,
        title: "دوره ها",
        href: "courses",
    },
    {
        id: 3,
        title: "علاقه مندی ها",
        href: "favorites",
    },
    {
        id: 4,
        title: "مالی و اشتراک",
        href: "transactions",
    },
    {
        id: 5,
        title: "دیدگاه و پرسش های شما",
        href: "questions",
    },
    {
        id: 6,
        title: "اعلانات",
        href: "notifications",
    },
    {
        id: 7,
        title: "ویرایش پروفایل",
        href: "edit",
    },
];

export const userCounterData: UserCounterItem[] = [
    {
        id: 1,
        title: "باقیمانده اشتراک",
        text: "عضو ویژه نیستید",
    },
    {
        id: 2,
        title: "در حال یادگیری",
        text: "7 دوره",
    },
    {
        id: 3,
        title: "امتیازات",
        text: "85,480 ستاره",
    },
    {
        id: 4,
        title: "موجودی کیف پول",
        text: "1,079,000 تومان",
    },
];

export const userComments: UserComment[] = [
    {
        id: 1,
        text: "من این دوره رو خریدم و میخوام نکست هم بعدا یادبگیرم چون نیاز بیشتری دارم به آموزش های این دوره میشه بدون اینکه نکست رو ببینم این دوره رو ببینم ؟",
        title: "دوره آموزش Composer",
        img: "/images/Courses/04.jpg",
        status: true,
        courseHref: "#",
    },
    {
        id: 2,
        text: "من این دوره رو خریدم و میخوام نکست هم بعدا یادبگیرم چون نیاز بیشتری دارم به آموزش های این دوره میشه بدون اینکه نکست رو ببینم این دوره رو ببینم ؟",
        title: "آموزش فلاتر از صفر",
        img: "/images/Courses/03.jpg",
        status: false,
        courseHref: "#",
    },
];

export const userNotifications: UserNotification[] = [
    {
        id: 1,
        title: "ورود به سیستم",
        text: "در صورتی که قکر میکنید این کار توسط شما انجام نشده هرچه سریعتر به بخش مدیریت نشست ها در بخش پنل کاربری خود در نابغه مراجعه کنید و نشست مورد نظر را حذف کنید .",
        time: "6",
    },
    {
        id: 2,
        title: "ورود به سیستم",
        text: "در صورتی که قکر میکنید این کار توسط شما انجام نشده هرچه سریعتر به بخش مدیریت نشست ها در بخش پنل کاربری خود در نابغه مراجعه کنید و نشست مورد نظر را حذف کنید .",
        time: "4",
    },
];

// Courses - Categories - Articles - MenuLinks - Services - Basket - Users -

export const adminPanelMenuItems = [
    {
        id: 8,
        title: "داشبورد",
        href: "/admin-panel",
    },
    {
        id: 1,
        title: "دوره ها",
        href: "/admin-panel/courses",
    },
    {
        id: 2,
        title: "دسته بندی ها",
        href: "/admin-panel/categories",
    },
    {
        id: 3,
        title: "مقاله ها",
        href: "/admin-panel/articles",
    },
    {
        id: 4,
        title: "خدمات",
        href: "/admin-panel/services",
    },
    {
        id: 5,
        title: "سفارشات",
        href: "/admin-panel/basket",
    },
    {
        id: 6,
        title: "منو",
        href: "/admin-panel/menus",
    },
    {
        id: 9,
        title: "زیرمنو",
        href: "/admin-panel/submenus",
    },
    {
        id: 10,
        title: "زیرمنو های فرعی",
        href: "/admin-panel/sub-submenus",
    },
    {
        id: 7,
        title: "کاربران",
        href: "/admin-panel/users",
    },
    {
        id: 11,
        title: "کامنت ها",
        href: "/admin-panel/comments",
    },
    {
        id: 12,
        title: "سرفصل ها",
        href: "/admin-panel/sessions",
    },
    {
        id: 13,
        title: "ویدیوها",
        href: "/admin-panel/videos",
    },
    {
        id: 14,
        title: "خروج از سیستم",
        href: "/",
    },
];
